version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      API_PORT: 8080
      REDIS_ADD: "redis-api-cache"
      MAIN_LOC: "Tehran"
      CACHE_TIME: 300
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    networks:
      redis_net:
        aliases: []
    depends_on:
      - redis-api-cache
  redis-api-cache:
    image: "redis:alpine3.18"
    command: redis-server --save 60 1 --loglevel warning
    expose:
      - "6379"
    volumes:
      - "redis_cache:/data"
    networks:
      redis_net:
        aliases: []

volumes:
  redis_cache:

networks:
  redis_net: